spring.application.name=demo

spring.security.user.name=harshitha
spring.security.user.password=hhhhhh

# Tell Spring how to find your database
spring.datasource.url=jdbc:postgresql://localhost:5432/telusko_db
spring.datasource.username=postgres
spring.datasource.password=0000

# Tell Hibernate to talk in 'PostgreSQL language'
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect